before:
  hooks:
    - make packr
builds:
  - binary: "terraform-provider-bless_{{ .Tag }}"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
release:
  github:
    owner: chanzuckerberg
    name: terraform-provider-bless
env_files:
  github_token: ~/.config/goreleaser/github_token
