builds:
  - binary: terraform-provider-bless
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
release:
  github:
    owner: chanzuckerberg
    name: terraform-provider-bless
