dist: trusty
language: go
install:
  - curl -fSL --retry 5 https://github.com/gobuffalo/packr/releases/download/v1.13.1/packr_1.13.1_linux_amd64.tar.gz | sudo tar zx -C /usr/bin/
jobs:
  include:
    - stage: test
      script: make test-ci
