dist: trusty
language: go
go:
  - "1.13.1"
install:
  - make setup
jobs:
  include:
    - name: lint
      stage: test
      script: make lint-ci
    - name: test
      stage: test
      script: make test-ci
