on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.1'
      - run: go version

      - name: lint
        run: make lint-ci
      - name: test
        run: make test-ci
