[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.7"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
